services:
  distributed-rate-limiter:
    image: node:20-alpine
    container_name: distributed-rate-limiter
    command: >
      ash -c "cd app && npm install && npm start"
    volumes:
      - ./distributed-rate-limiter:/app # 挂載本地目錄到容器 即時更新
    ports:
      - "3000:3000" # 映射容器的 3000
    environment:
      # 將連線地址設定為 host.docker.internal
      # 這會讓容器連線到你的本機電腦
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379