services:
  distributed-rate-limiter:
    image: node:20-alpine
    container_name: distributed-rate-limiter
    command: >
      ash -c "cd app && npm install && npm start"
    volumes:
      - ./distributed-rate-limiter:/app # 挂載本地目錄到容器 即時更新
    network_mode: host # 使用主機網路模式