apiVersion: v1
kind: Service
metadata:
  name: rate-limiter
  labels:
    app: rate-limiter
  namespace: dev
spec:
  selector:
    app: rate-limiter # 匹配 Deployment 中的 labels
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80 # Service 的端口
      targetPort: 80 # Pod 中容器的端口
