apiVersion: v1
kind: Pod
metadata:
  name: simple-server
  labels:
    app: simple-server
  namespace: dev
spec:
  containers:
    - name: simple-server
      image: hanbro0112/simple-server:latest
      ports:
        - containerPort: 80